services:
    backend:
        # PENTING: Update Dockerfile di GitHub Anda menggunakan versi "All-in-One"
        # agar image ini berisi (Nginx + PHP-FPM + build Vite).
        image: ghcr.io/esareynor/ffws-jatim-backend:${BACKEND_IMAGE_TAG}
        container_name: ffws-backend
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "3001:80" # Ubah ke 80 karena Backend sekarang sudah ada Nginx di dalamnya
        volumes:
            - ./backend-storage:/var/www/storage
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            - public_net

    frontend:
        # PENTING: Update Dockerfile di GitHub Anda menggunakan versi "Multi-stage build"
        image: ghcr.io/esareynor/ffws-jatim-frontend:${FRONTEND_IMAGE_TAG}
        container_name: ffws-frontend
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "3000:80"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            - public_net

networks:
    public_net:
        external: true
